# See https://github.com/silverstripe/silverstripe-travis-support for setup details

sudo: false

language: php

php:
  - 5.6
  - 7.0
  - 7.1

env:
  - DB=MYSQL CORE_RELEASE=4
  - DB=PGSQL CORE_RELEASE=4

before_script:
  - composer self-update || true
  - git clone git://github.com/silverstripe/silverstripe-travis-support.git ~/travis-support
  - php ~/travis-support/travis_setup.php --source `pwd` --target ~/builds/ss
  - cd ~/builds/ss
  - composer install --prefer-dist --no-progress --no-suggest
  - composer require silverstripe/versioned:1.x-dev --prefer-dist --no-progress --no-suggest
  - composer dump-autoload --optimize

script:
  - vendor/bin/phpunit gridfieldextensions/tests
